export const REFRESH = () => "REFRESH_STATE";
export const MODIFY = "USER_EDIT";
export const LOGIN = () => "USER_LOGIN";
export const USERNAME_FETCH = () => "USERNAME_FETCH";
export const FETCH_PROFILE = () => "FETCH_PROFILE";
export const UPDATE = () => "USER_UPDATE";
export const FETCH_UPDATE = () => "FETCH_USER_UPDATE";
export const LOGOUT = () => "USER_LOGOUT";
export const REGISTER = () => "USER_REGISTER";
export const SUCCESS = () => "SUCCESS";
export const ERROR = () => "ERROR";
export const ExternalError = () => "External_Error";
